/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.latihan.belajarswingworker.form;

import com.latihan.belajarswingworker.dao.Daokaryawan;
import com.latihan.belajarswingworker.domain.Karyawan;
import com.latihan.belajarswingworker.util.Koneksi;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Artha
 */
public class TampilData extends javax.swing.JFrame {
    private Daokaryawan daokaryawan;
    private DefaultTableModel model;
    SwingWorker<Boolean,Karyawan> worker;
    /**
     * Creates new form TampilData
     */
    public TampilData() {
        initComponents();
        daokaryawan=Koneksi.getDaokaryawan();
        model = (DefaultTableModel) tblKaryawan.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTampil = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        btnStop = new javax.swing.JButton();
        btnTanpaWorker = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Belajar Swing Worler");

        btnTampil.setText("Tampil Data");
        btnTampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTampilActionPerformed(evt);
            }
        });

        progressBar.setStringPainted(true);

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Alamat", "Tanggal Lahir", "Telephone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblKaryawan);

        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnTanpaWorker.setText("Tanpa Worker");
        btnTanpaWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanpaWorkerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnTampil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop)
                        .addGap(48, 48, 48)
                        .addComponent(btnTanpaWorker)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTampil)
                    .addComponent(btnStop)
                    .addComponent(btnTanpaWorker))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTampilActionPerformed
        
        worker = new SwingWorker<Boolean, Karyawan>() {

            @Override
            protected Boolean doInBackground() throws Exception {
                List<Karyawan> karyawans = daokaryawan.getKaryawans();
                int i = 0;
                int total = karyawans.size();
                int persen = 0;
                for(Karyawan k : karyawans ){
                    persen = (i * 100) / total;
                    System.out.println("Persen : " + persen + " | i : " + i);
                    progressBar.setValue(persen);
                    i++;
                    publish(k);
                    Thread.sleep(100);
                }
                return true;
            }

            @Override
            protected void process(List<Karyawan> chunks) {
                Karyawan karyawan=chunks.get(chunks.size()-1);
                model.addRow(new Object[]{karyawan.getNama(),karyawan.getAlamat(),karyawan.getTanggalLahir(),karyawan.getTelephone() });
                int indexRow = model.getRowCount()-1;
                int indexColumn = model.getColumnCount()-1;
                tblKaryawan.scrollRectToVisible(tblKaryawan.getCellRect(indexRow, indexColumn, true));
                tblKaryawan.setRowSelectionInterval(indexRow, indexRow);
            }

            @Override
            protected void done() {
                JOptionPane.showMessageDialog(null, "Process done..","Information",JOptionPane.INFORMATION_MESSAGE);
            }
        };
        worker.execute();
    }//GEN-LAST:event_btnTampilActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if (worker!=null){
            worker.cancel(true);
            progressBar.setValue(100);
        }
    }//GEN-LAST:event_btnStopActionPerformed

    private void btnTanpaWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanpaWorkerActionPerformed
        List<Karyawan> karyawans = daokaryawan.getKaryawans();
        for(Karyawan k : karyawans){
            model.addRow(new Object[]{k.getNama(),k.getAlamat(),k.getTanggalLahir(),k.getTelephone() });
            int indexRow = model.getRowCount()-1;
            int indexColumn = model.getColumnCount()-1;
            tblKaryawan.scrollRectToVisible(tblKaryawan.getCellRect(indexRow, indexColumn, true));
            tblKaryawan.setRowSelectionInterval(indexRow, indexRow);
        }
    }//GEN-LAST:event_btnTanpaWorkerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStop;
    private javax.swing.JButton btnTampil;
    private javax.swing.JButton btnTanpaWorker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTable tblKaryawan;
    // End of variables declaration//GEN-END:variables
}
